services:
  users:
    build: ./users
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/users
    networks:
      - microservices-net

  invoices:
    build: ./invoices
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/invoices
    networks:
      - microservices-net

  products:
    build: ./products
    ports:
      - "3003:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/products
    networks:
      - microservices-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - microservices-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: invoices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
